# Generated by Django 2.1.2 on 2018-10-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_openendedanswer_ratinganswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='openendedquestion',
            name='type',
            field=models.CharField(default='open_ended', max_length=25),
        ),
        migrations.AddField(
            model_name='ratingquestion',
            name='type',
            field=models.CharField(default='rating', max_length=25),
        ),
    ]
